CASE: BERT_GNN
ACTION: predict_single
# ----- Model config -----:
MODEL_NAME: normal_QK_model
ATOM_FEATURES:
  - AtomicNum
  - ChiralTag
  - Hybridization
  - FormalCharge
  - NumImplicitHs
  - ExplicitValence
  - Mass
  - IsAromatic
BOND_FEATURES:
  - BondType
  - Stereo
  - IsAromatic
RESTORE_FILE: <path_to_trained_model_checkpoint>.pkl
# ----- Graph config -----: 
LINE_GRAPH: false
LINE_GRAPH_MAX_SIZE_MULTIPLIER: 5
SELF_LOOPS: false
# ----- Run config -----:
BATCH_SIZE: 200
LOADER_OUTPUT_TYPE: jax
N_PARTITIONS: 0
PADDING_N_EDGE: 256
PADDING_N_NODE: 128
# PYTABLE_FROM_DISK: false
RETURN_INTERMEDIATES: true
# ----- Train config -----:
CLASS_ALPHA: null
LEARNING_RATE: 0.001
# LOG_IMAGES_FREQUENCY: 50
# LOSS_OPTION: cross_entropy
# N_EPOCH: 10
OPTIMIZATION:
  OPTION: adam_transformer
  WARMUP_STEPS: 6000
  TRANSITION_EPOCHS: 500
# SAVE_FREQUENCY: 50
# ----- Size cut config -----:
# BIG_BATCH_SIZE: 20
# BIG_PADDING_N_EDGE: 256
# BIG_PADDING_N_NODE: 128
# BIG_SWITCH_EPOCH: 2
# BIG_TRAIN_CSV_NAME: .csv
# BIG_VALID_CSV_NAME: .csv
SIZE_CUT_DIRNAME: null
# ----- Logging config -----:
LOGGING_PARENT_DIR: /media/driveWD12/matej/Documents/repos/MatejHl/Receptor_odorant/Receptor_odorant/JAX/TESTING/ICLR2023/_predictions/_single
# ----- Data config -----:
TRAIN_CSV_NAME: .csv
VALID_CSV_NAME: .csv
PREDICT_CSV_NAME: .csv
DATACASE: chemosimdb/<folder_with_data_csvs>
DATA_PARENT_DIR: /mnt_other/Receptor_odorant/Receptor_odorant/JAX/BERT_GNN/Data
SEQ_ID: OR6F1
MUTATED_SEQUENCE: MDTGNKTLPQDFLLLGFPGSQTLQLSLFMLFLVMYILTVSGNVAILMLVSTSHQLHTPMYFFLSNLSFLEIWYTTAAVPKALAILLGRSQTISFTSCLLQMYFVFSLGCTEYFLLAAMAYDRCLAICYPLHYGAIMSSLLSAQLALGSWVCGFVAIAVPTALISGLSFCGPRAINHFFCDIAPWIALACTNTQAVELVAFVIAVVVILSSCLITFVSYVYIISTILRIPSASGRSKAFSTCSSHLTVVLIWYGSTVFLHVRTSIKDALDLIKAVHVLNTVVTPVLNPFIYTLRNKEVRETLLKKWKGK
MOL_ID: ULDHMXUKGWMISQ-SECBINFHSA-N_R_carvone
SMILES: CC1=CC[C@H](CC1=O)C(=C)C