CASE: BERT_GNN
ACTION: train
# ----- Model config -----:
MODEL_NAME: DummyModel
ATOM_FEATURES:
  - AtomicNum
  - ChiralTag
  - Hybridization
  - FormalCharge
  - NumImplicitHs
  - ExplicitValence
  - Mass
  - IsAromatic
BOND_FEATURES: []
RESTORE_FILE: null
# ----- Graph config -----:
LINE_GRAPH: true
LINE_GRAPH_MAX_SIZE_MULTIPLIER: 5
SELF_LOOPS: false
# ----- Run config -----:
BATCH_SIZE: -1
LOADER_OUTPUT_TYPE: tf
N_PARTITIONS: 0
PADDING_N_EDGE: -1
PADDING_N_NODE: -1
PYTABLE_FROM_DISK: false
RETURN_INTERMEDIATES: false
# ----- Train config -----:
CLASS_ALPHA: null
LEARNING_RATE: -1.0
LOG_IMAGES_FREQUENCY: -1
LOSS_OPTION: cross_entropy
N_EPOCH: -1
OPTIMIZATION:
  OPTION: adam_transformer
  WARMUP_STEPS: 6000
  TRANSITION_EPOCHS: 500
SAVE_FREQUENCY: -1
# ----- Size cut config -----:
BIG_BATCH_SIZE: -1
BIG_PADDING_N_EDGE: -1
BIG_PADDING_N_NODE: -1
BIG_SWITCH_EPOCH: -1
BIG_TRAIN_CSV_NAME: .csv
BIG_VALID_CSV_NAME: .csv
SIZE_CUT_DIRNAME: ""
# ----- Logging config -----:
LOGGING_PARENT_DIR: ""
# ----- Data config -----:
TRAIN_CSV_NAME: .csv
VALID_CSV_NAME: .csv
PREDICT_CSV_NAME: .csv
BERT_H5FILE: ""
DATACASE: ""
LABEL_COL: Responsive
MOL_COL: _SMILES
SEQ_COL: null
SEQ_ID_COL: seq_id
VALID_WEIGHT_COL: null
WEIGHT_COL: null
